// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using OpsICO.Core.Data;
using OpsICO.Core.Enums;
using System;

namespace Nethereum.BlockChainStore.Core.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20180516122544_TokenContractAddress")]
    partial class TokenContractAddress
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OpsICO.Core.Entities.NodeBlock", b =>
                {
                    b.Property<int>("NodeBlockID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BlockHash");

                    b.Property<int>("BlockNumber");

                    b.Property<DateTime>("BlockTime");

                    b.Property<string>("Nonce");

                    b.Property<string>("ParentHash");

                    b.Property<int>("TransactionCount");

                    b.HasKey("NodeBlockID");

                    b.ToTable("NodeBlock");
                });

            modelBuilder.Entity("OpsICO.Core.Entities.NodeTokenTransfer", b =>
                {
                    b.Property<int>("NodeTokenTransferID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Amount");

                    b.Property<string>("From");

                    b.Property<int>("NodeTransactionID");

                    b.Property<string>("To");

                    b.Property<string>("TokenContractAddress");

                    b.HasKey("NodeTokenTransferID");

                    b.HasIndex("NodeTransactionID");

                    b.ToTable("NodeTokenTransfer");
                });

            modelBuilder.Entity("OpsICO.Core.Entities.NodeTransaction", b =>
                {
                    b.Property<int>("NodeTransactionID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("From");

                    b.Property<int>("NodeBlockID");

                    b.Property<int>("Status");

                    b.Property<string>("To");

                    b.Property<string>("TxHash");

                    b.Property<decimal>("Value");

                    b.HasKey("NodeTransactionID");

                    b.HasIndex("NodeBlockID");

                    b.ToTable("NodeTransaction");
                });

            modelBuilder.Entity("OpsICO.Core.Entities.NodeTokenTransfer", b =>
                {
                    b.HasOne("OpsICO.Core.Entities.NodeTransaction", "NodeTransaction")
                        .WithMany("NodeTokenTransfers")
                        .HasForeignKey("NodeTransactionID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("OpsICO.Core.Entities.NodeTransaction", b =>
                {
                    b.HasOne("OpsICO.Core.Entities.NodeBlock", "NodeBlock")
                        .WithMany("NodeTransactions")
                        .HasForeignKey("NodeBlockID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
